# When manually running the pipeline, you can select whether it
# succeeds or fails.
parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job: installnotnetcorecli
  steps:
   - task: DotNetCoreCLI@2
     inputs:
       command: 'build'

- job: installnpm
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
      checkLatest: true
  - task: Npm@1
    inputs:
      command: 'install'
 