version: '2'
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    hostname: rabbitmq-server
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=bsjc
      - RABBITMQ_DEFAULT_PASS=bsjc
    restart: always
    volumes:
      - 'rabbitmq_data:/bitnami'
volumes:
  rabbitmq_data:
    driver: local
